name: Deploy Backend

on:
  push:
    branches: [main]
    paths:
      - "tocopedia-backend/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/tocopedia
            git pull origin main
            cd tocopedia-backend

            cat > .env <<EOL
            PORT=3000
            MONGODB_URL=${{ secrets.MONGODB_URL }}
            JWT_SECRET=${{ secrets.JWT_SECRET }}
            CLOUDFLARE_TUNNEL_TOKEN=${{ secrets.CLOUDFLARE_TUNNEL_TOKEN }}
            EOL

            docker compose -f docker-compose.prod.yml down
            docker compose -f docker-compose.prod.yml up -d --build
