name: Deploy Backend

on:
  push:
    branches: [main]
    paths:
      - "tocopedia-backend/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/tocopedia
            git pull origin main
            cd tocopedia-backend
            docker compose down
            docker compose up -d --build
